//
//  Resources.swift
//  PointeuseDeTemps
//
//  Created by Benoît Goossens on 15/08/18.
//  Copyright © 2018 Benoît Goossens. All rights reserved.
//

import Foundation

let RSC_ACTIVITYNAME = "Nom de l'activité"
let RSC_ACTIVITY_ORDER = "Ordre de l'activité"
let RSC_GPSPOSITION = "Position GPS"
let RSC_ACTIVITIES_MANAGEMENT = "Gestion des activités"
let RSC_ADD = "Ajout"
let RSC_OK = "Ok"
let RSC_CANCEL = "Annuler"
let RSC_SELECTPICTURE = "Sélection d'une image"
let RSC_SELECTMEDIA = "Choisirle média :"
let RSC_PHOTOLIBRARY = "Librairie de photos"
let RSC_CAMERA = "Appareil photo"
let RSC_ERROR = "Erreur"
let RSC_LOGIN_REQUIRED = "Le login est obligatoire"
let RSC_PASSWORD_REQUIRED = "Le mot de passe est obligatoire"
let RSC_ERR_USERCREATIONFAILED = "La création de l'utilisateur a échoué !"
let RSC_CONNECTION = "Connexion"
let RSC_LOGIN = "Login"
let RSC_PASSWORD = "Mot de passe"
let RSC_WELCOME = "Bienvenue"
let RSC_USERCREATION = "Création d'un utilisateur"
let RSC_USER_UNKNOWED = "L'utilisateur référencé n'est pas connu"
let RSC_WRONG_PASSWORD = "Le mot de passe renseigné n'est pas correct"
let RSC_IDENTIFICATION = "Identification"
let RSC_SAVE_ERROR = "Erreur lors de la sauvegarde"
let RSC_DELETE_ERROR = "Erreur lors de la suppression"
let RSC_SAVE_OK = "Sauvegarde réalisée avec succès"
let RSC_DELETE_OK = "Suppression réalisée avec succès"
let RSC_INFORMATION = "Information"
let RSC_LASTNAME = "Nom"
let RSC_FIRSTNAME = "Prénom"
let RSC_SAVE = "Sauvegarder"
let RSC_DECONNECTION = "Déconnexion"
let RSC_DELETE = "Suppression"
let RSC_USER = "Utilisateur"
let RSC_ACTIVITIES = "Activités"
let RSC_DAYS = "Journées"
let RSC_TIMESCORE = "Pointage"
let RSC_HISTORY = "Historique"
let RSC_NUMBER_OF_ACTIVITIES = "Nombre d'activité(s) : "
let RSC_TYPICAL_DAY = "Journée type"
let RSC_LISTOFACTIVITIES = "Activités :"
let RSC_ACTIVATE = "Activer"
let RSC_SELECTIONOFACTIVITY = "Sélection de l'activité à ajouter :"
let RSC_SELECTIONOFTYPICALDAY = "Sélection de la journée type à ajouter :"
let RSC_ORDER = "Ordre"
let RSC_HOURS = "heure(s)"
let RSC_MINUTES = "minute(s)"
let RSC_SECONDS = "seconde(s)"
let RSC_START = "Début"
let RSC_END = "Fin"
let RSC_LATITUDE = "Lat.:"
let RSC_LONGITUDE = "Long.:"
let RSC_DURATION = "Durée"
let RSC_ACTIVITYDETAILS = "Détails de l'activité"
let RSC_ERROR_ORDEREXISTS = "Le numéro d'ordre existe déjà"
let RSC_ERROR_ACTIVITYNAMEEXISTS = "Le nom de l'activité existe déjà"
let RSC_NODURATION = "Aucun temps pour cet élément"
let RSC_TOTALDURATION = "Durée totale"
let RSC_RUNNING = "En cours"
let RSC_DESACTIVATE = "Désactiver"
let RSC_EMAIL = "Email"
let RSC_SYNCHRONIZATION = "Synchronisation des données"
let RSC_ALLOW_MESSAGES = "Autoriser les messages"
let RSC_MAIL_REQUIRED = "L'adresse mail est obligatoire"
let RSC_SYNCHRONIZATION_ERROR = "Erreur de synchronisation"
let RSC_CREATEUSERFROMSERVER = "Création d'un utilisateur\ndepuis le serveur"
let RSC_CREATIONFROMSERVER = "Création depuis le serveur"
let RSC_NOUSERONSERVER = "Aucun utilisateur n'existe sur le serveur pour le login et l'email renseigné"
let RSC_USERCREATIONFAILED = "La création de l'utilisateur a échoué"
let RSC_USERCREATIONFROMSERVERSUCCEED = "La création de l'utilisateur a réussi. Vous pouvez maintenant vous connecter avec cet utilisateur."
let RSC_NOT_DEFINED = "Non dédini"
let RSC_USER_LOGIN_EXIST_LOCALLY = "Un utilisateur existe déjà sur l'appareil avec ce login"
let RSC_USER_MAIL_EXIST_LOCALLY = "Un utilisateur existe déjà sur l'appareil avec ce mail"
let RSC_CREATION = "Création"
let RSC_USER_MAIL_EXIST_ONSERVER = "Un utilisateur existe déjà sur le serveur avec ce login et/ou ce mot de passe"
let RSC_FRIENDS = "Amis"
let RSC_SELECTIONOFUSER = "Sélection de l'utilisateur à ajouter :"
let RSC_ACTIVE = "Actif"
let RSC_INACTIVE = "Inactif"
let RSC_MESSAGES = "Messages"
let RSC_THE = "Le "
let RSC_YESTERDAY = "Hier : "
